#!/bin/sh
# Heavily inspired by https://github.com/wbolster/pyenv-no-global-pip

set -eu

RED='\033[0;31m'
NO_COLOR='\033[0m'
ME=`basename ${0}`

printf "${RED}${ME}: error: invoked outside a virtual environment... aborting!${NO_COLOR}\n"
exit 1

