#!/bin/sh

set -eu
set -x

sudo launchctl config user umask 077

echo "Configuring..."
sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "Eric Hansander <eric@hansander.com>"

echo "- keyboard"
defaults write -g KeyRepeat -int 2
defaults write -g InitialKeyRepeat -int 15
defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g NSAutomaticCapitalizationEnabled -bool false
defaults write -g NSAutomaticDashSubstitutionEnabled -bool false
defaults write -g NSAutomaticPeriodSubstitutionEnabled -bool false
defaults write -g NSAutomaticQuoteSubstitutionEnabled -bool false

echo "- mouse, trackpad"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write -g com.apple.mouse.tapBehavior -int 1
defaults write -g com.apple.mouse.tapBehavior -int 1

defaults write -g com.apple.trackpad.scaling -float 1.0
defaults write -g com.apple.mouse.scaling -float 1.5

echo "- appearance"
defaults write -g AppleShowScrollBars -string "WhenScrolling"
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
defaults write -g NSWindowResizeTime -float 0.001

defaults write com.apple.airplay showInMenuBarIfPresent -bool true

echo "- sounds"
defaults write com.apple.systemsound com.apple.sound.uiaudio.enabled -bool false
defaults write -g com.apple.sound.beep.feedback -bool false
# Disable the sound effects on boot
sudo nvram SystemAudioVolume=" "

echo "- built in apps"
defaults write com.apple.notificationcenterui bannerTime 2
defaults write com.apple.screencapture include-date -bool false
defaults write com.apple.screencapture location -string "${HOME}/Downloads"

# Display crash reports in Notification Center (instead of dialog)
defaults write com.apple.CrashReporter UseUNC 1

defaults write com.apple.TextEdit RichText -int 0
defaults write com.apple.TextEdit ShowRuler -bool false

echo "- security, login"
sudo defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool false

defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
defaults write -g RetriesUntilHint -int 0

defaults write com.apple.screensaver askForPassword -bool true
defaults write com.apple.screensaver askForPasswordDelay -int 0

echo "- Dock"
defaults write com.apple.Dock autohide-delay -float 0
defaults write com.apple.Dock launchanim -bool false
defaults write com.apple.Dock expose-animation-duration -float 0.1
defaults write com.apple.Dock showhidden -bool true
defaults write com.apple.Dock 'orientation' -string 'left'
defaults write com.apple.Dock tilesize -int 32
defaults write com.apple.Dock largesize -float 48
defaults write com.apple.Dock magnification -bool true
# Remove all (default) app icons from the Dock
defaults write com.apple.Dock persistent-apps -array
defaults write com.apple.Dock 'checked-for-launchpad' -bool true
killall Dock

echo "- Finder"
defaults write com.apple.Finder AppleShowAllFiles -bool true
defaults write com.apple.Finder DisableAllAnimations -bool true
defaults write com.apple.Finder _FXSortFoldersFirst -bool true
defaults write com.apple.Finder QLEnableTextSelection -bool true
defaults write com.apple.Finder ShowStatusBar -bool true
defaults write com.apple.Finder ShowPathbar -bool true

defaults write com.apple.Finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.Finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.Finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.Finder ShowRemovableMediaOnDesktop -bool true

# New window target
# Computer     : `PfCm`
# Volume       : `PfVo`
# $HOME        : `PfHm`
# Desktop      : `PfDe`
# Documents    : `PfDo`
# All My Files : `PfAF`
# Other…       : `PfLo`
defaults write com.apple.Finder NewWindowTarget -string 'PfLo'
defaults write com.apple.Finder NewWindowTargetPath -string "file://${HOME}/Downloads/";

# Preferred view style
# Icon View   : `icnv`
# List View   : `Nlsv`
# Column View : `clmv`
# Cover Flow  : `Flwv`
# After configuring preferred view style, clear all `.DS_Store` files
# to ensure settings are applied for every directory
# sudo find / -name ".DS_Store" -delete
defaults write com.apple.Finder FXPreferredViewStyle -string "Nlsv"

defaults write -g AppleShowAllExtensions -bool true
defaults write -g QLPanelAnimationDuration -float 0

chflags nohidden ~/Library/
killall Finder

echo "- Other settings"
# disable sleep and standby completely when charger is connected
pmset -c sleep 0 # default 20
pmset -c standby 0 #default 1
